### ISSUE TITLE
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds

### ISSUE THREAD

**Issue by 1286169349** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#15]
Traceback (most recent call last):
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 654, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _run_sanity_check
    val_loop.run()
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1703, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/trainers/rag_executor.py", line 168, in validation_step
    return self._generative_step(sample_batched, batch_idx)
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/trainers/rag_executor.py", line 199, in _generative_step
    generation_outputs = self.model.generate(**test_batch)
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/rag/rag_model.py", line 406, in generate
    generation_outputs = self.generator.generate(**test_batch) 
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/transformers/generation_utils.py", line 990, in generate
    return self.greedy_search(
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/transformers/generation_utils.py", line 1292, in greedy_search
    outputs = self(
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1399, in forward
    decoder_outputs = self.decoder(
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/zzu_zxw/miniconda3/envs/RAVQA/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 900, in forward
    raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds

**Comment by 1286169349** [comment]
我只能本地加载模型，我把她-large下载到了我的本地路径中。
请问是我的生成器加载错了吗：
        # Initialising generator
        # GeneratorModelClass = globals()[self.config.model_config.GeneratorModelClass]#GeneratorModelClass='T5ForConditionalGeneration'
        # GeneratorConfigClass = globals()[self.config.model_config.GeneratorConfigClass]#GeneratorConfigClass='T5Config'
        # generator_model_config = GeneratorConfigClass.from_pretrained(self.config.model_config.GeneratorModelVersion)#GeneratorModelVersion=t5-large
        # self.generator = GeneratorModelClass.from_pretrained(self.config.model_config.GeneratorModelVersion,config=generator_model_config)

        # 指定模型的本地路径
        models_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/t5-large"
        self.generator = T5Model.from_pretrained(models_path)

**Comment by 1286169349** [comment]
我只能本地加载模型，我把t5-large下载到了我的本地路径中。
请问是我的生成器加载错了吗：
# Initialising generator
# GeneratorModelClass = globals()[self.config.model_config.GeneratorModelClass]#GeneratorModelClass='T5ForConditionalGeneration'
# GeneratorConfigClass = globals()[self.config.model_config.GeneratorConfigClass]#GeneratorConfigClass='T5Config'
# generator_model_config = GeneratorConfigClass.from_pretrained(self.config.model_config.GeneratorModelVersion)#GeneratorModelVersion=t5-large
# self.generator = GeneratorModelClass.from_pretrained(self.config.model_config.GeneratorModelVersion,config=generator_model_config)

    # 指定模型的本地路径
    models_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/t5-large"
    self.generator = T5Model.from_pretrained(models_path)

**Comment by 1286169349** [comment]
我只能本地加载模型，我把t5-large下载到了我的本地路径中。   请问是我的生成器加载错了吗：
# Initialising generator
# GeneratorModelClass = globals()[self.config.model_config.GeneratorModelClass]#GeneratorModelClass='T5ForConditionalGeneration'
# GeneratorConfigClass = globals()[self.config.model_config.GeneratorConfigClass]#GeneratorConfigClass='T5Config'
# generator_model_config = GeneratorConfigClass.from_pretrained(self.config.model_config.GeneratorModelVersion)#GeneratorModelVersion=t5-large
# self.generator = GeneratorModelClass.from_pretrained(self.config.model_config.GeneratorModelVersion,config=generator_model_config)

 # 指定模型的本地路径
 models_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/t5-large"
 self.generator = T5Model.from_pretrained(models_path)

**Comment by 1286169349** [comment]
我只能本地加载模型，我把t5-large下载到了我的本地路径中。 请问是我的生成器加载错了吗：
# Initialising generator
        # GeneratorModelClass = globals()[self.config.model_config.GeneratorModelClass]#GeneratorModelClass='T5ForConditionalGeneration'
        # GeneratorConfigClass = globals()[self.config.model_config.GeneratorConfigClass]#GeneratorConfigClass='T5Config'
        # generator_model_config = GeneratorConfigClass.from_pretrained(self.config.model_config.GeneratorModelVersion)#GeneratorModelVersion=t5-large
        # self.generator = GeneratorModelClass.from_pretrained(self.config.model_config.GeneratorModelVersion,config=generator_model_config)

        # 指定模型的本地路径
        models_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/t5-large"
        self.generator = T5Model.from_pretrained(models_path)

**Comment by LinWeizheDragon** [comment]
Could you please try `T5ForConditionalGeneration.from_pretrained` and downgrade the transformers version to a lower one?

**Comment by 1286169349** [comment]
Yes,you're right!
